version: "3"
services:
    wordpress:
        image: visiblevc/wordpress

        # required for mounting bindfs
        cap_add:
            - SYS_ADMIN
        devices:
            - /dev/fuse
        # required on certain cloud hosts
        security_opt:
            - apparmor:unconfined

        ports:
            - 8082:80
        volumes:
            - ./data:/data
            - ./froda/froda:/app/wp-content/themes/froda
        environment:
            DB_NAME: froda
            DB_PASS: root
            PLUGINS: >-
                optimus
                redirection
                regenerate-thumbnails
                relevanssi
                safe-svg
                simple-custom-post-order
                wordpress-seo
                [advanced-custom-fields-pro]http://www.stok.se/plugin-repo/advanced-custom-fields-pro.zip
                [wp-migrate-db-pro]http://www.stok.se/plugin-repo/wp-migrate-db-pro-1.8.1.zip
                [wp-migrate-db-pro-cli]http://www.stok.se/plugin-repo/wp-migrate-db-pro-cli-1.3.2.zip
                [wp-migrate-db-pro-media-files]http://www.stok.se/plugin-repo/wp-migrate-db-pro-media-files-1.4.9.zip
                [polylang-pro]http://www.stok.se/plugin-repo/polylang-pro.zip
            URL_REPLACE: http://localhost:8082
            WP_DEBUG: 'true'

    db:
        image: mariadb:10 # or mysql:5.7
        volumes:
            - data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - 22224:80

volumes:
    data: