version: "3"
services:
    wordpress:
        image: visiblevc/wordpress

        # required for mounting bindfs
        cap_add:
            - SYS_ADMIN
        devices:
            - /dev/fuse
        # required on certain cloud hosts
        security_opt:
            - apparmor:unconfined

        ports:
            - 8085:80
        volumes:
            - ./data:/data
            - ./code/hbon_wp_discover/wordpress/wp-content/plugins/level3-cdn:/app/wp-content/plugins/level3-cdn
            - ./code/hbon_wp_discover/wordpress/wp-content/themes/hbo-discover-v3:/app/wp-content/themes/hbo-discover-v3
            - ./code/plugins/polylang-wpai-master:/app/wp-content/plugins/polylang-wpai-master
            - ./code/plugins/wp-all-export-pro:/app/wp-content/plugins/wp-all-export-pro
            - ./code/plugins/wp-all-import-pro:/app/wp-content/plugins/wp-all-import-pro
            - ./code/vendor:/app/vendor
        environment:
            DB_NAME: mno_ua
            DB_PASS: root
            PLUGINS: >-
                classic-editor
                [papi]https://github.com/wp-papi/papi/archive/master.zip
                [polylang-pro]http://www.stok.se/plugin-repo/polylang-pro.zip
            URL_REPLACE: http://localhost:8085
            WP_DEBUG: 'false'

    db:
        image: mariadb:10 # or mysql:5.7
        volumes:
            - data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - 22227:80

volumes:
    data: